### ISSUE TITLE
How can pods be configured on the management cluster to use harbor?

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#96]
- Which configuration needs to take place so that we are able to use harbor as a registry to pull from?
- Which risks are there if harbor becomes unavailable?

**Comment by cagiti** [comment]
For info: https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_create_secret_docker-registry/

**Comment by MarcelMue** [comment]
https://github.com/giantswarm/rfc/pull/49

**Comment by DeeAjayi** [comment]
For pods to be able to pull images from harbor, they have to be authenticated against the registry. 

When using docker as the container runtime, there are two ways I found that it can be done right now:

1. Create a docker-registry secret with the harbor registry credentials and then reference the `imagePullSecrets` parameter in places where an image will need to be pulled from (Pods, Deployments etc). This doesn't look like a viable solution because it would require a secret to be created in each namespace and also have the secret referenced.
2. The second option is to configure the default service account to reference the secret, this is more viable because we won't need to reference the `imagePullSecrets` in our manifest files. 

A way around having to set the secret across multiple namespaces is to use an operator like the [Imagepullsecret-patcher](https://github.com/titansoft-pte-ltd/imagepullsecret-patcher) to set the secret and also add the secret reference to the default ServiceAccount on all namespaces. We can create the secret and configure the [Imagepullsecret-patcher](https://github.com/titansoft-pte-ltd/imagepullsecret-patcher) operator in the harbor-operator-app helm chart but can only work for MC and not WC because we're not deploying harbor on WC.

When configuring with containerd, we can create a secret in a `cluster-$provider` helm chart and reference the registry credentials as done [here](https://github.com/giantswarm/cluster-aws/pull/160). This looks like a more seamless solution than what we have with docker

**Comment by DeeAjayi** [comment]
looping you in here @kubasobon

**Comment by MarcelMue** [comment]
We have worked through the containerd configuration on WC clusters. We can do the same on management clusters.
